### ISSUE TITLE
Remove aws region `current` boolean Deprecated in AWS provider

### ISSUE THREAD

**Issue by disaac** [unifio/terraform-aws-apigw#9]
[terraform-provider-aws PR #3157](https://github.com/terraform-providers/terraform-provider-aws/pull/3157) deprecated the need for defining `current` if an `endpoint` and name are omitted. 

* Updated [terraform-provider-aws v1.9.0](https://github.com/terraform-providers/terraform-provider-aws/tree/v1.9.0) now displays deprecation warning.
```
Warning: module.apigw_acct.data.aws_region.current: "current": [DEPRECATED] Defaults to current provider region if no other filtering is enabled
```
* Should be removed to support latest and avoid deprecation warning: 
[DEPRECATED](https://github.com/unifio/terraform-aws-apigw/blob/3e81a10ea1be1d2de6e59f0911ef90097419f48d/account/main.tf#L8)

**Comment by yuhunglin** [comment]
@disaac should be resolved with #10 and referencing the new tag: https://github.com/unifio/terraform-aws-apigw/releases/tag/v0.1.5
